config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'cosmes/index'
  get '/cosme/personalcolor', to: "cosmes#personalcolor"
  root to: "cosmes#index"
  resources :users, only: [:show]
  resources :cosmes, only: [:index, :new, :create, :show, :update, :edit, :destroy]do
    resources :comments, only: [:create]
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :cosme

  validates :text, presence: true
end

app/models/cosme.rb
class Cosme < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :image
  belongs_to :personalcolor

  with_options presence: true do
    validates :title
    validates :text
    validates :image
    validates :personalcolor_id, numericality: { other_than: 1 }
  end

  def self.search(search)
    if search != ''
      Cosme.where(['text LIKE ? OR title LIKE ?', "%#{search}%", "%#{search}%"])
    else
      Cosme.all
    end
  end
end

app/models/personalcolor.rb
class Personalcolor < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'イエベ春' },
    { id: 3, name: 'ブルベ夏' },
    { id: 4, name: 'イエベ秋' },
    { id: 5, name: 'ブルベ冬' },
    { id: 6, name: 'どなたにも似合う' }
  ]

  include ActiveHash::Associations
  has_many :cosmes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments
  has_many :cosmes

  validates :name, presence: true, length: { maximum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to cosme_path(@comment.cosme)
    else
      @cosme = @comment.cosme
      @comments = @cosme.comments
      render 'cosmes/show'
    end
  end

  def show
    @comments = @cosme.comments
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, cosme_id: params[:cosme_id])
  end
end

app/controllers/cosmes_controller.rb
class CosmesController < ApplicationController
  before_action :cosme_find, only: [:show, :edit, :update, :destroy]
  before_action :search_personalcolor_cosme, only: [:index, :personalcolor]

  def index
    @cosmes = Cosme.all
  end

  def new
    @cosme = Cosme.new
  end

  def create
    @cosme = Cosme.new(cosme_params)
    if @cosme.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @cosme.comments
  end

  def edit
  end

  def update
    if @cosme.update(cosme_params)
      redirect_to cosme_path(@cosme.id)
    else
      render :edit
    end
  end

  def destroy
    @cosme.destroy
    redirect_to root_path
  end

  def search
    @cosmes = Cosme.search(params[:keyword])
  end

  def personalcolor
    @cosmes = @q.result
    personalcolor_id = params[:q][:personalcolor_id_eq]
    @personalcolor = Personalcolor.find_by(id: personalcolor_id)
  end

  private

  def cosme_params
    params.require(:cosme).permit(:name, :image, :text, :title, :personalcolor_id).merge(user_id: current_user.id)
  end

  def cosme_find
    @cosme = Cosme.find(params[:id])
  end

  def search_personalcolor_cosme
    @q = Cosme.ransack(params[:q])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @cosmes = @user.cosmes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/cosmes_helper.rb
module CosmesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cosmes/_cosme.html.erb
<div class="card">
  <%= link_to image_tag(cosme.image, class: :card__img ), cosme_path(cosme.id)%>
  <div class="card__body">
    <%= link_to cosme.title, cosme_path(cosme.id), class: :card__title%>
    <%= cosme.personalcolor.name %>
  </div>
</div>

app/views/cosmes/_form.html.erb
<%= form_with model: @cosme, local: true do |f|%>
    <div class="field">
      <%= f.label :title, "タイトル" %><br />
      <%= f.text_field :title, id:"cosme_title", class:"cosme_title"%>
    </div> 
    
    <div class="field">
      <%= f.label :text, "紹介文など記入してください" %><br />
      <%= f.text_area :text, class: :form__text, id:"cosme_text", class:"cosme_text" %>
    </div>

    <div class="field">
      <%= f.label :image, "画像" %><br />
      <%= f.file_field :image, id:"cosme_image", class:"cosme_image"%>
    </div>

    <div class="field">
    <%= f.label :personalcolor_id, "おすすめパーソナルカラー" %><br />
    <%= f.collection_select(:personalcolor_id, Personalcolor.all, :id, :name, {}, {class:"color-select"}) %>
    </div>

    <div class="actions">
      <%= f.submit "コスメを投稿", class:"form__btn" %>
    </div>
<% end %>

app/views/cosmes/edit.html.erb
<div class="container" style="background-image: url(<%= asset_path "image2.jpg" %>);">
    <p>cosme編集</p>
    <%= render partial: "form", locals: { cosme: @cosme } %>
</div>

app/views/cosmes/index.html.erb
<main class="main">
  <div class="inner">
  <%= form_with(url: search_cosmes_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "コスメを検索する", class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
  <% end %>
  <%= search_form_for @q, url: cosme_personalcolor_path, class: "search-form" do |f| %>
    <%= f.collection_select :personalcolor_id_eq, Personalcolor.where.not(id: 0), :id, :name, include_blank: "パーソナルカラー検索" %>
    <%= f.submit '検索', class: "search-btn" %>
<% end %>

  <% if user_signed_in? %>
      <div class="greeting">
       今日もメイクを楽しみましょう
      <%= link_to "#{current_user.name}さん", user_path(current_user.id), class: :greeting__link%>
      </div>
  <% end %>
    <div style="position: relative; display:inline-block;">
      <img src="/images/index.jpg" alt="", class="image">
    <div class="font" style="position: absolute; top: 450px; left: 200px; max-width: 100%; max-height: 100%; padding: 30px; text-align: left;">
      <p>みんなのお気に入りコスメを投稿しよう</p>
    </div></div>
      <div class="card__wrapper">
      <%= render partial: 'cosme', collection: @cosmes %>
    </div>
  </div>
</main>

app/views/cosmes/new.html.erb
<div class="container" style="background-image: url(<%= asset_path "image2.jpg" %>);">
    <p>投稿する</p>
    <%= render partial: "form", locals: { cosme: @cosme } %>
</div>

app/views/cosmes/personalcolor.html.erb
<%= search_form_for @q, url: cosme_personalcolor_path, class: "search-form" do |f| %>
    <%= f.collection_select :personalcolor_id_eq, Personalcolor.where.not(id: 0), :id, :name, include_blank: "パーソナルカラー検索" %>
    <%= f.submit '検索', class: "search-btn" %>
<% end %>
    <div class="contents row">
        <% @cosmes.each do |cosme| %>
              <%= render partial: "cosme", locals: { cosme: cosme } %>
        <% end %>
    </div>

app/views/cosmes/search.html.erb
<%= form_with(url: search_cosmes_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "コスメを検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @cosmes.each do |cosme| %>
    <%= render partial: "cosme", locals: { cosme: cosme } %>
  <% end %>
</div>

app/views/cosmes/show.html.erb
<main class="main">
  <div class="inner">
    <div class="cosme__wrapper">
      <p class="cosme__hedding">
        <%= @cosme.title%>
      </p>
      <%= link_to "by#{@cosme.user.name}", user_path(@cosme.user.id), class:"cosme__user" %>
      <% if user_signed_in? && current_user.id == @cosme.user_id %>
        <div class="cosme__manage">
          <%= link_to "編集する", edit_cosme_path(@cosme.id), class: :cosme__manage %>
          <%= link_to "削除する", cosme_path(@cosme.id), class: :cosme__manage, method: :delete%>
        </div>
      <% end %>
      <div class="cosme_imagewrapper">
        <%= image_tag @cosme.image, class:"cosme__image" %>
      </div>
      <div class="cosme__body">
        <div class="cosme__detail">
          <p class="detail__title">タイトル</p>
          <p class="detail__message">
            <%= @cosme.title %>
          </p>
        </div>

        <div class="cosme__detail">
        <p class="detail__title">おすすめパーソナルカラー</p>
        <%= @cosme.personalcolor.name %>
      </div>

        <div class="cosme__detail">
          <p class="detail__title">コスメの紹介文</p>
          <p class="detail__message">
            <%= @cosme.text %>
          </p>
        </div>
      </div>
      <div class="cosme__comments">
        <% if user_signed_in? %>
          <%= form_with(model: [@cosme,@comment],local: true) do |f|%>
            <div class="field">
              <%= f.label :text, "コメント", class:"text" %><br />
              <%= f.text_field :text, id:"comment_text", class: :coment_text %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %> 
        <% end %> 
           <ul class="comments_lists">
            <% @comments.each do |comment| %>
            <li class="comments_list"> 
                  <%= comment.text %>
                  <%= link_to "by #{comment.user.name}", "/users/#{comment.user_id}", class: :comment_user %>
                   </li>
                <% end %>
              </ul>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>		
<html>
  <head>
    <meta charset="UTF-8">
    <head>
    <title>Cosmelog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- header -->
    <div id="wrapper">
    <header>
      <h1 class="headline">
      <%= link_to "cosmelog", root_path, class: :nav_listitem %>
      </h1>
      <div class="nav_list">
      <% if user_signed_in? %>
          <div class="nav_listitem">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete%>
            <%= link_to "投稿する", new_cosme_path, class: :nav_listitem %>
          </div>
        <% else %>
          <div class="nav_listitem">
            <%= link_to "ログイン", new_user_session_path, class: :nav_listitem %>
            <%= link_to "新規登録", new_user_registration_path, class: :nav_listitem %>
          </div>
        <% end %>
      </div>
    </header>
    <!-- サイトの中身部分 -->
    <%= yield %>
    <!-- footer -->
    <footer>
      <ul class="footer-menu">
      <ul class="footer-menu">
      </ul>
      <p>
      Copyright cosmelog 2021.
      </p>
    </footer>
  </body>
</html>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
      <br>
        <%= "#{@user.name}さんの情報"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">登録名</th>
            <td class="table__col2"><%= @user.name %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.name}さんの投稿コスメ"%>
      </h2>
      <br>
      <div class="user__card">
      <%= render partial: 'cosmes/cosme', collection: @cosmes %>
        <%# 部分テンプレートでそのユーザーが投稿したプロトタイプ投稿一覧を表示する %>
      </div>
    </div>
  </div>
</div>